InvalidFormData: Invalid form data
MissingForm: Missing form
SelectedTime: Selected time
LoginToIdentifyCustomer: Please login to identify the customer
AlreadyHaveAnAccount: Already have an account
ContactUs: Contact Us
LoginToSeeYourProfile: Please login to see your profile 
End: End
UserProfile: User profile
RescheduleAppointment: Reschedule appointment
CancelAppointment: Cancel appointment
Appointment: Appointment
NoAppointmentsYet: You have no appointments yet
LoginToSeeYourAppointments: Please login to see your appointments
MyAppointments: My appointments
Time: Time
Day: Day
NotYourAccount: Not your account
Continue: Continue
Next: Next
StepNofM n@Int m@Int: Step #{show n} of #{show m} 
MyContacts: My contacts
TellUsAboutYourself: Tell us about yourself
CustomerInformation: Customer information
Proceed: Proceed
SelectedStaff: Selected staff
SelectedServices: Selected services
SignUpToContinue: Sign up to continue
ReceptionTime: Reception time
AppointmentTime: Appointment time
SelectAtLeastOneServicePlease: Please select at least one service
SelectStaff: Select staff
MaximumAvailability: Maximum availability
NoPreference: No preference
NoStaffAvailable: No staff available
SymbolMinute: min
SymbolHour: h
InvalidDurationHourMinute duration@Text: Invalid duration: #{duration}. Expected pattern HH:MM
Duration: Duration
Offers: Offers
Offer: Offer
ChooseServices: Choose services
ChooseServicesToBook: Choose services to book
ChooseService: Choose a service
ChooseServiceToBook: Choose a service to book
Unregister: Unregister
NoServicesFound: No services found
Administrator: Administrator
Customer: Customer
NoUsersFound: No users found
More: More
Favicon: Favicon
NoBrandYet: There is no brand yet
BrandStrapline: Brand strapline
BrandName: Brand name
BrandMark: Brand mark
Brand: Brand
ValueNotInRange rstart@Int rend@Int: Value not in range #{show rstart}..#{show rend}
InvalidValue: Invalid value
Unregistered: Unregistered
Registered: Registered
AccountStatus: Account status
Employed: Employed
Dismissed: Dismissed
Select: Select
Status: Status
NoStaffMembersFound: No staff members found
Search: Search
UnregisterAreYouSure: Are you sure you want to unregister user?
RegisterAsUser: Register as user
PasswordChanged: Password changed
NewPassword: New password
ResetPassword: Reset password
NoUsersYet: There are no users yet
User: User
Users: Users
Contact: Contact
AlreadyExists: Already exists
Content: Content
NoContentYet: There is no content yet
SourceCode: Source code
ErdDiagram: ERD Diagram
Resources: Resources
RoleAlreadyInTheList: Role already in the list
Ratings: Ratings
Rating: Rating
AddRole: Add role
NoRolesYes: There are no roles yet
BookAppointment: Book an appointment
EmployeeAlreadyInTheList: Employee already in the list
Mobile: Mobile
Phone: Phone
Role: Role
Roles: Roles
Employee: Employee
NoStaffYet: There is no staff yet
AddStaffMember: Add staff member
Staff: Staff
No: No
Yes: Yes
Unpublished: Unpublished
Published: Published
Overview: Overview
PriceAlreadyInTheList: This price is already in the list
Registration: Registration
Authentication: Authentication
NoPriceSetYet: No price has been set for the service
AddPrice: Add price
Pricelist: Pricelist
ServisAlreadyInTheList: This service is already in the list
DuplicateValue: Duplicate value
Suffix: Suffix
Prefix: Prefix
PleaseConfirm: Please confirm
YesDelete: Delete
DeleteAreYouSure: Are you sure you want to delete?
AddService: Add service
AddSubservice: Add subservice
Subservices: Subservices
Category: Category
Categories: Categories
Image: Image
NoServicesYet: There are not services yet
RecordDeleted: Record deleted
RecordEdited: Record edited
RecordAdded: Record added
Thumbnail: Thumbnail
Price: Price
Description: Description
TheName: Name
Name: Name
PasswordsDoNotMatch: Passwords don't match
YouMustEnterTwoValues: You must enter two values
Email: Email
FullName: Full name
Photo: Photo
Save: Save
Cancel: Cancel
Account: Account
DoNotHaveAnAccount: Don't have an account?
AsAdmin: As admin
CreateAccount: Create account
SignInToYourAccount: Sign in to your account
SignIn: Sign in
SignUp: Sign up
Logout: Logout
Login: Login
ConfirmPassword: Confirm password
Password: Password
Username: Username
Book: Book
Add: Add
Data: Data
Welcome: Welcome
AboutUs: About Us
Service: Service
Services: Services
Salon: Salon
AppName: Salon
MetaKeywords: beauty, salon, application
MetaDescription: Beauty Salon Application

Documentation: Docs
Doc001: The "Salon" application provides the ability to publish and advertise the services of beauty salon owners on the web.