NoBusinessAddressFound: No business address found
ShowAddress: Show address
NoBusinessHoursFound: No business hours found
Sunday: Sunday
Saturday: Saturday
Friday: Friday
Thursday: Thursday
Wednesday: Wednesday
Tuesday: Tuesday
Monday: Monday
PatternHourMinute: HH:MM
Latitude: Latitude
Longitude: Longitude
ShowMap: Show map
ShowSchedule: Show schedule
NumberOfOrders: Number of orders
ValueOfOrders: Value of orders
TotalOrderValue: Total order value
ServiceRanking: Service ranking
AcronymAOV: AOV
AverageOrderValue: Average order value
BasicEntities: Basic Entities
BusinessDay: Business day
SortDescending: Sort descending
SortAscending: Sort ascending
Sort: Sort
Workday: Workday
TimeSlot: Time slot
CustomerRanking: Customer ranking
TotalScheduledTime: Total scheduled time
TotalBookedTime: Total booked time
NoDataFound: No data found
BetweenTo: To
BetweenFrom: From
Period: Period
ChoosePeriod: Choose period
CompletionTime: Completion time
Today: Today
Mon: Mon
Tue: Tue 
Wed: Wed
Thu: Thu
Fri: Fri
Sat: Sat
Sun: Sun
List: List
InvalidTimeInterval: Invalid time interval
Holiday: Holiday
Weekend: Weekend
Weekday: Weekday
DayType: Day type
BusinessHours: Business hours
NoBusinessScheduleYet: No business schedule yet
BusinessDays: Business days
Details: Details
EndTime: End time
StartTime: Start time
WorkingHours: Working hours
NoScheduleYet: There is no schedule yet
WorkSchedule: Schedule
AddWorkingHours: Add working hours
Workload: Workload
NumberSign: ##
Bookings: Bookings
NoDataToDisplay: No data to display
PopularOffers: Popular offers
Analytics: Analytics
NoAppointmentsFound: No appointments found
MarkWidth: Mark width
MarkHeight: Mark height
Currency: Currency
Unavailable: Unavailable
Available: Available
TheFullName: Full name
NoCategoriesFound: No categories found
NoOffersFound: No offers found
Unassigned: Unassigned
AreYouSureYouWantToTakeOnThisTask: Are you sure you want to take on this task?
AssignToMe: Assign to Me
Nonexpert: You are not listed as an expert for this service
Back: Back
Close: Close
Edit: Edit
Del: Delete
NavigationMenu: Navigation menu
OnlyEmployeesMaySeeRequests: Only employees may see requests
YouAreNotAnEmployeeOfFacility: You are not an employee of this facility 
InvalidBusinessTimeZone: Invalid business time zone
InvalidBusinessTimeZoneOffset: Invalid business time zone offset
InvalidBusinessAddress: Invalid business address
PreviouslySelected: Previously selected
TimeZoneOffset: Time zone offset
AddExpert: Add expert
NoExpertsYet: There are no experts yet
Expert: Expert
Experts: Experts
Current: Current
NoAssigneeRequestReschedule: If you reschedule this request, the task will be assigned to you
NoAssigneeRequestApprove: If you approve this request, the task will be assigned to you
Adjusted: Adjusted
FinishAppointmentConfirm: Please confirm that the customer's request has been fulfilled and paid
RequestFinish: Finish
BusinessAlreadyExists: Business already exists
NoBusinessYet: There is no business yet
Business: Business
Address: Address
Location: Location
ApproveAppointmentConfirm: Please confirm that you approve this appointment request
FromCoworkers: From coworkers
DemoUserAccounts: Demo user accounts
WithoutAssignee: Without assignee
AssignedToMe: Assigned to me
Assignee: Assignee
ShowAll: Show all
Approve: Approve
Request: Request
LoginToSeeTheRequests: Please login to see the requests
NoRequestsFound: No requests found
NoPendingRequestsYet: No requests for approval yet
NoRequestsYet: There are no requests yet
AppointmentStateDiagram: State transition diagram for appointment
NoHistoryYet: There is no history yet
History: History
EntityNotFound: Entity not found
LoginBanner loginHref@Text: Please <a href=#{loginHref}>login</a> to perform the action
LoginToPerformAction: Please login to perform the action
CancelAppointmentReally: Do you really want to cancel this appointment?
Acquaintance: Acquaintance
SayHelloTo: Say hello to
Paid: Paid
Cancelled: Cancelled
Approved: Approved
AwaitingApproval: Awaiting approval
AppoinmentStatus: Status
Meeting: Meeting
MeetingTime: Meeting time
MeetingLocation: Meeting location
Nullify: Nullify
Reschedule: Reschedule
Calendar: Calendar
BookingCalendar: Booking calendar
Requests: Requests
BookingRequests: Booking requests
NoOffersYet: There are no offers yet
ChoosePhoto: Choose photo
ChooseImage: Choose image
Attribution: Attribution
AddOffer: Add offer
Minutes: Minutes
TimeZone: Time zone
AppointmentTimeIsInThePast: Appointment time is in the past
AppointmentDayIsInThePast: Appointment day is in the past
BookingSequenceRestarted: Booking sequence restarted
StartAnew: Start anew
InvalidBookingEntryPoint: Invalid entry point for booking
BookNewAppointment: Book new appointment 
ShowDetails: Show details
YouSuccessfullyCreatedYourBooking: You successfully created your booking
BookingStateDiagram: State transition diagram for booking
InvalidFormData: Invalid form data
MissingForm: Missing form
SelectedTime: Selected time
LoginToIdentifyCustomer: Please login to identify the customer
AlreadyHaveAnAccount: Already have an account
ContactUs: Contact Us
LoginToSeeYourProfile: Please login to see your profile 
End: End
UserProfile: User profile
RescheduleAppointment: Reschedule appointment
CancelAppointment: Cancel
Appointment: Appointment
NoAppointmentsYet: You have no appointments yet
LoginToSeeYourAppointments: Please login to see your appointments
MyAppointments: My appointments
Time: Time
Date: Date
Day: Day
NotYourAccount: Not your account
Continue: Continue
Next: Next
StepNofM n@Int m@Int: Step #{show n} of #{show m} 
MyContacts: My contacts
TellUsAboutYourself: Tell us about yourself
CustomerInformation: Customer information
Proceed: Proceed
SelectedStaff: Selected staff
SelectedServices: Selected services
SignUpToContinue: Sign up to continue
ReceptionTime: Reception time
AppointmentTime: Appointment time
SelectAtLeastOneServicePlease: Please select at least one service
SelectStaff: Select staff
MaximumAvailability: Maximum availability
NoPreference: No preference
NoStaffAvailable: No staff available
SymbolMinute: min
SymbolHour: h
InvalidDurationHourMinute duration@Text: Invalid duration: #{duration}. Expected pattern HH:MM
Duration: Duration
Offers: Offers
Offer: Offer
ChooseServices: Choose services
ChooseServicesToBook: Choose services to book
ChooseService: Choose a service
ChooseServiceToBook: Choose a service to book
Unregister: Unregister
NoServicesFound: No services found
Administrator: Administrator
Customer: Customer
NoUsersFound: No users found
More: More
Favicon: Favicon
NoBrandYet: There is no brand yet
BrandStrapline: Brand strapline
BrandName: Brand name
BrandMark: Brand mark
Brand: Brand
ValueNotInRange rstart@Int rend@Int: Value not in range #{show rstart}..#{show rend}
InvalidValue: Invalid value
Unregistered: Unregistered
Registered: Registered
AccountStatus: Account status
Employed: Employed
Dismissed: Dismissed
Select: Select
Status: Status
NoStaffMembersFound: No staff members found
Search: Search
UnregisterAsUser: Unregister as user
UnregisterAreYouSure: Are you sure you want to unregister user?
RegisterAsUser: Register as user
PasswordChanged: Password changed
NewPassword: New password
ResetPassword: Reset password
NoUsersYet: There are no users yet
User: User
Users: Users
Contact: Contact
AlreadyExists: Already exists
Content: Content
NoContentYet: There is no content yet
SourceCode: Source code
ErdDiagram: ERD Diagram
Resources: Resources
ExpertAlreadyInTheList: Expert already in the list
RoleAlreadyInTheList: Role already in the list
Ratings: Ratings
Rating: Rating
AddRole: Add role
NoRolesYet: There are no roles yet
BookAppointment: Book appointment
EmployeeAlreadyInTheList: Employee already in the list
Mobile: Mobile
Phone: Phone
Role: Role
Roles: Roles
Employee: Employee
NoStaffYet: There is no staff yet
AddStaffMember: Add staff member
Staff: Staff
No: No
Yes: Yes
Unpublished: Unpublished
Published: Published
Overview: Overview
PriceAlreadyInTheList: This price is already in the list
Registration: Registration
Authentication: Authentication
NoPriceSetYet: No price has been set for the service
AddPrice: Add price
Pricelist: Pricelist
ServisAlreadyInTheList: This service is already in the list
DuplicateValue: Duplicate value
Suffix: Suffix
Prefix: Prefix
PleaseConfirm: Please confirm
YesDelete: Delete
DeleteAreYouSure: Are you sure you want to delete?
AddService: Add service
AddSubservice: Add subservice
Subservices: Subservices
Category: Category
Categories: Categories
Image: Image
NoServicesYet: There are not services yet
RecordDeleted: Record deleted
RecordEdited: Record edited
RecordAdded: Record added
Thumbnail: Thumbnail
Price: Price
Description: Description
TheName: Name
Name: Name
PasswordsDoNotMatch: Passwords don't match
YouMustEnterTwoValues: You must enter two values
Email: Email
FullName: Full name
Photo: Photo
Save: Save
Cancel: Cancel
Account: Account
DoNotHaveAnAccount: Don't have an account?
AsAdmin: As admin
CreateNewAccount: Create new account
CreateAccount: Create account
SignInToYourAccount: Sign in to your account
SignIn: Sign in
SignUp: Sign up
Logout: Logout
Login: Login
ConfirmPassword: Confirm password
Password: Password
Username: Username
Book: Book
Add: Add
Data: Data
Welcome: Welcome
AboutUs: About Us
Service: Service
Services: Services
Salon: Salon
AppName: Salon
MetaKeywords: beauty, salon, application
MetaDescription: Beauty Salon Application

Documentation: Docs
Doc001 hrefHome@Text: The <a href=#{hrefHome}>"Salon"</a> application provides the opportunity to publish and advertise the services of beauty salon owners on the web.

Doc002 hrefServices@Text: The services to be advertised are defined and published in section <a href=#{hrefServices}>"Services"</a> of group "Data". Optionally, services can be defined as a hierarchy of groups and subservices.

Doc003: Each service can have multiple offers with corresponding prices and currencies. Offers are defined for each Service in the “Services” section in the “Data” group.

Doc004 hrefServices@Text hrefBook@Text: Once the service and its offerings are defined, the service can be published. The service and offers will be displayed to the customer in the section <a href=#{hrefServices}>"Services"</a> and available for booking in the section <a href=#{hrefBook}>"Book appointment"</a>.

Doc005 hrefBusiness@Text: Detailed information about the business can be provided in the section <a href=#{hrefBusiness}>"Business"</a> of the group "Data" in the main menu.

Doc0061 hrefSchedule@Text hrefBusiness@Text: Additionally, from the tab <a href=#{hrefSchedule}>"Schedule"</a> in the section <a href=#{hrefBusiness}>"Business"</a>, the organization's work schedule for each day can be added.

Doc0062 hrefBusiness@Text: Additionally, from the tab "Schedule" in the section <a href=#{hrefBusiness}>"Business"</a>, the organization's work schedule for each day can be added.

Doc0063 hrefAboutUs@Text hrefBusiness@Text: The "About Us" page can be customized from the <a href=#{hrefAboutUs}>"About Us"</a> tab in the menu <a href=#{hrefBusiness}>"Business"</a> in the group "Data".

Doc0064 hrefBusiness@Text: The "About Us" page can be customized from the "About Us" tab in the menu <a href=#{hrefBusiness}>"Business"</a> in the group "Data".

Doc0065 hrefContactUs@Text hrefBusiness@Text: The "Contacts" page can be customized from the <a href=#{hrefContactUs}>"Contact Us"</a> tab in the menu <a href=#{hrefBusiness}>"Business"</a> in the group "Data".

Doc0066 hrefBusiness@Text: The "Contacts" page can be customized from the "Contact Us" tab in the menu <a href=#{hrefBusiness}>"Business"</a> in the group "Data".

Doc0067 hrefHome@Text hrefBrand@Text hrefBusiness@Text: The <a href=#{hrefHome}>“Home”</a> page is customizable from the <a href=#{hrefBrand}>“Brand”</a> tab of the <a href=#{hrefBusiness}>“Business”</a> menu in the “Data” group.

Doc0068 hrefHome@Text hrefBusiness@Text: The <a href=#{hrefHome}>“Home”</a> page is customizable from the “Brand” tab of the <a href=#{hrefBusiness}>“Business”</a> menu in the “Data” group.

Doc007: Currently, the app only supports one business. Multi-business support is planned for future versions of the application.

Doc008 href@Text: Application users, including clients, employees and administrators, can be registered through the <a href=#{href}>"Registration"</a> form.

Doc009 href@Text: Users can also be managed by administrators in the section <a href=#{href}>“Users”</a> of the group “Data”.