OnlyEmployeesMaySeeRequests: Only employees may see requests
YouAreNotAnEmployeeOfFacility: You are not an employee of this facility 
InvalidBusinessTimeZone: Invalid business time zone
InvalidBusinessTimeZoneOffset: Invalid business time zone offset
InvalidBusinessAddress: Invalid business address
PreviouslySelected: Previously selected
TimeZoneOffset: Time zone offset
AddExpert: Add expert
NoExpertsYet: There are no experts yet
Expert: Expert
Experts: Experts
Current: Current
NoAssigneeRequestReschedule: If you reschedule this request, the task will be assigned to you
NoAssigneeRequestApprove: If you approve this request, the task will be assigned to you
Adjusted: Adjusted
FinishAppointmentConfirm: Please confirm that the customer's request has been fulfilled and paid
RequestFinish: Finish
BusinessAlreadyExists: Business already exists
NoBusinessYet: There is no business yet
Business: Business
Address: Address
Location: Location
ApproveAppointmentConfirm: Please confirm that you approve this appointment request
FromCoworkers: From coworkers
DemoUserAccounts: Demo user accounts
WithoutAssignee: Without assignee
AssignedToMe: Assigned to me
Assignee: Assignee
ShowAll: Show all
Approve: Approve
Request: Request
LoginToSeeTheRequests: Please login to see the requests
NoRequestsFound: No requests found
NoPendingRequestsYet: No requests for approval yet
NoRequestsYet: There are no requests yet
AppointmentStateDiagram: State transition diagram for appointment
NoHistoryYet: There is no history yet
History: History
EntityNotFound: Entity not found
LoginBanner loginHref@Text: Please <a href=#{loginHref}>login</a> to perform the action
LoginToPerformAction: Please login to perform the action
CancelAppointmentReally: Do you really want to cancel this appointment?
Acquaintance: Acquaintance
SayHelloTo: Say hello to
Paid: Paid
Cancelled: Cancelled
Approved: Approved
AwaitingApproval: Awaiting approval
AppoinmentStatus: Status
Meeting: Meeting
MeetingTime: Meeting time
MeetingLocation: Meeting location
Nullify: Nullify
Reschedule: Reschedule
Calendar: Calendar
BookingCalendar: Booking calendar
Requests: Requests
BookingRequests: Booking requests
NoOffersYet: There are no offers yet
ChoosePhoto: Choose photo
ChooseImage: Choose image
Attribution: Attribution
AddOffer: Add offer
Minutes: Minutes
TimeZone: Time zone
AppointmentTimeIsInThePast: Appointment time is in the past
AppointmentDayIsInThePast: Appointment day is in the past
BookingSequenceRestarted: Booking sequence restarted
StartAnew: Start anew
InvalidBookingEntryPoint: Invalid entry point for booking
BookNewAppointment: Book new appointment 
ShowDetails: Show details
YouSuccessfullyCreatedYourBooking: You successfully created your booking
BookingStateDiagram: State transition diagram for booking
InvalidFormData: Invalid form data
MissingForm: Missing form
SelectedTime: Selected time
LoginToIdentifyCustomer: Please login to identify the customer
AlreadyHaveAnAccount: Already have an account
ContactUs: Contact Us
LoginToSeeYourProfile: Please login to see your profile 
End: End
UserProfile: User profile
RescheduleAppointment: Reschedule appointment
CancelAppointment: Cancel
Appointment: Appointment
NoAppointmentsYet: You have no appointments yet
LoginToSeeYourAppointments: Please login to see your appointments
MyAppointments: My appointments
Time: Time
Date: Date
Day: Day
NotYourAccount: Not your account
Continue: Continue
Next: Next
StepNofM n@Int m@Int: Step #{show n} of #{show m} 
MyContacts: My contacts
TellUsAboutYourself: Tell us about yourself
CustomerInformation: Customer information
Proceed: Proceed
SelectedStaff: Selected staff
SelectedServices: Selected services
SignUpToContinue: Sign up to continue
ReceptionTime: Reception time
AppointmentTime: Appointment time
SelectAtLeastOneServicePlease: Please select at least one service
SelectStaff: Select staff
MaximumAvailability: Maximum availability
NoPreference: No preference
NoStaffAvailable: No staff available
SymbolMinute: min
SymbolHour: h
InvalidDurationHourMinute duration@Text: Invalid duration: #{duration}. Expected pattern HH:MM
Duration: Duration
Offers: Offers
Offer: Offer
ChooseServices: Choose services
ChooseServicesToBook: Choose services to book
ChooseService: Choose a service
ChooseServiceToBook: Choose a service to book
Unregister: Unregister
NoServicesFound: No services found
Administrator: Administrator
Customer: Customer
NoUsersFound: No users found
More: More
Favicon: Favicon
NoBrandYet: There is no brand yet
BrandStrapline: Brand strapline
BrandName: Brand name
BrandMark: Brand mark
Brand: Brand
ValueNotInRange rstart@Int rend@Int: Value not in range #{show rstart}..#{show rend}
InvalidValue: Invalid value
Unregistered: Unregistered
Registered: Registered
AccountStatus: Account status
Employed: Employed
Dismissed: Dismissed
Select: Select
Status: Status
NoStaffMembersFound: No staff members found
Search: Search
UnregisterAreYouSure: Are you sure you want to unregister user?
RegisterAsUser: Register as user
PasswordChanged: Password changed
NewPassword: New password
ResetPassword: Reset password
NoUsersYet: There are no users yet
User: User
Users: Users
Contact: Contact
AlreadyExists: Already exists
Content: Content
NoContentYet: There is no content yet
SourceCode: Source code
ErdDiagram: ERD Diagram
Resources: Resources
ExpertAlreadyInTheList: Expert already in the list
RoleAlreadyInTheList: Role already in the list
Ratings: Ratings
Rating: Rating
AddRole: Add role
NoRolesYes: There are no roles yet
BookAppointment: Book appointment
EmployeeAlreadyInTheList: Employee already in the list
Mobile: Mobile
Phone: Phone
Role: Role
Roles: Roles
Employee: Employee
NoStaffYet: There is no staff yet
AddStaffMember: Add staff member
Staff: Staff
No: No
Yes: Yes
Unpublished: Unpublished
Published: Published
Overview: Overview
PriceAlreadyInTheList: This price is already in the list
Registration: Registration
Authentication: Authentication
NoPriceSetYet: No price has been set for the service
AddPrice: Add price
Pricelist: Pricelist
ServisAlreadyInTheList: This service is already in the list
DuplicateValue: Duplicate value
Suffix: Suffix
Prefix: Prefix
PleaseConfirm: Please confirm
YesDelete: Delete
DeleteAreYouSure: Are you sure you want to delete?
AddService: Add service
AddSubservice: Add subservice
Subservices: Subservices
Category: Category
Categories: Categories
Image: Image
NoServicesYet: There are not services yet
RecordDeleted: Record deleted
RecordEdited: Record edited
RecordAdded: Record added
Thumbnail: Thumbnail
Price: Price
Description: Description
TheName: Name
Name: Name
PasswordsDoNotMatch: Passwords don't match
YouMustEnterTwoValues: You must enter two values
Email: Email
FullName: Full name
Photo: Photo
Save: Save
Cancel: Cancel
Account: Account
DoNotHaveAnAccount: Don't have an account?
AsAdmin: As admin
CreateAccount: Create account
SignInToYourAccount: Sign in to your account
SignIn: Sign in
SignUp: Sign up
Logout: Logout
Login: Login
ConfirmPassword: Confirm password
Password: Password
Username: Username
Book: Book
Add: Add
Data: Data
Welcome: Welcome
AboutUs: About Us
Service: Service
Services: Services
Salon: Salon
AppName: Salon
MetaKeywords: beauty, salon, application
MetaDescription: Beauty Salon Application

Documentation: Docs
Doc001: The application "Salon" provides the ability to publish and advertise the services of beauty salon owners on the web.

Doc002 hrefServices@Text: The services to be advertised are defined in section <a href=#{hrefServices}>"Services"</a> of group "Data". Optionally, services can be defined as a hierarchy of groups and subservices.