AddStaffMember: Ajouter un membre
Staff: Personnelle
No: Non
Yes: Oui
Published: Publié
Overview: Aperçu
PriceAlreadyInTheList: Ce prix est déjà dans la liste
Registration: Inscription
Authentication: Authentification
NoPriceSetYet: Aucun prix n'a été fixé pour le service
AddPrice: Ajouter prix
Pricelist: Liste de prix
ServisAlreadyInTheList: Ce service est déjà dans la liste
DuplicateValue: Valeur en double
Suffix: Suffixe
Prefix: Préfixe
PleaseConfirm: Veuillez confirmer
YesDelete: Supprimer
DeleteAreYouSure: Etes-vous sûr que vous voulez supprimer?
AddService: Ajouter service
AddSubservice: Ajouter sous-service
Subservices: Sous-services
Category: Catégorie
Image: Image
NoServicesYet: Il n'y a pas encore de services
RecordDeleted: L'enregistrement a été supprimé
RecordEdited: L'enregistrement a été modifié
RecordAdded: Enregistrement ajouté
Thumbnail: Vignette
Price: Prix
Description: Description
TheName: Nom
Name: Nom
PasswordsDoNotMatch: Les mots de passe ne correspondent pas
YouMustEnterTwoValues: Vous devez entrer deux valeurs
Email: E-mail
FullName: Nom et prénom
Photo: Photo
Save: Enregistrer
Cancel: Annuler
Account: Compte
DoNotHaveAnAccount: Vous n'avez pas de compte ?
AsAdmin: Comme administrateur
CreateAccount: Créer un compte
SignInToYourAccount: Connectez-vous à votre compte
SignIn: Connectez-vous
SignUp: S'inscrire
Logout: Se déconnecter
Login: Connexion
ConfirmPassword: Confirmez le mot de passe
Password: Mot de passe
Username: Nom d'utilisateur
Book: Réserver
Add: Ajouter
Data: Donnés
Welcome: Bienvenue
AboutUs: À propos de nous
Service: Service
Services: Services
Salon: Salon