OnlyEmployeesMaySeeRequests: Seuls les employés peuvent voir les demandes
YouAreNotAnEmployeeOfFacility: Vous n'êtes pas un employé de cet établissement
InvalidBusinessTimeZone: Fuseau horaire professionnel non valide
InvalidBusinessTimeZoneOffset: Décalage de fuseau horaire professionnel non valide
InvalidBusinessAddress: Adresse professionnelle invalide
PreviouslySelected: Précédemment sélectionné
TimeZoneOffset: Décalage de fuseau horaire
AddExpert: Ajouter un expert
NoExpertsYet: Il n'y a pas encore d'experts
Expert: Expert
Experts: Experts
Current: Actuel
NoAssigneeRequestReschedule: Si vous reprogrammez cette demande, la tâche vous sera attribuée
NoAssigneeRequestApprove: Si vous confirmer cette demande, la tâche vous sera transférée
Adjusted: Ajusté
FinishAppointmentConfirm: Veuillez confirmer que la demande du client a été satisfaite et payée
RequestFinish: Finir
BusinessAlreadyExists: L'entreprise existe déjà
NoBusinessYet: Il n'y a pas encore d'entreprise
Business: Entreprise
Address: Adresse
Location: Lieu
ApproveAppointmentConfirm: Veuillez confirmer que vous approuvez cette demande de rendez-vous
FromCoworkers: Des collègues
DemoUserAccounts: Comptes utilisateurs démo
WithoutAssignee: Sans exécuteur
AssignedToMe: Assigné à moi
Assignee: Désigné
ShowAll: Afficher tout
Approve: Approuver
Request: Demande
LoginToSeeTheRequests: Veuillez vous connecter pour voir les demandes
NoRequestsFound: Aucune demande trouvée
NoPendingRequestsYet: Il n'y a pas encore de demandes d'approbation
NoRequestsYet: Il n'y a pas encore de demandes
AppointmentStateDiagram: Diagramme de transition d'état de rendez-vous
NoHistoryYet: Il n'y a pas encore d'historique
History: L'histoire
EntityNotFound: Entité introuvable
LoginBanner loginHref: Veuillez vous <a href=#{loginHref}>connecter</a> pour effectuer l'action
LoginToPerformAction: Veuillez vous connecter pour effectuer l'action
CancelAppointmentReally: Voulez-vous vraiment annuler ce rendez-vous ?
Acquaintance: Faire connaissance
SayHelloTo: Dire bonjour à
Paid: Payé
Cancelled: Annulé
Approved: Approuvé
AwaitingApproval: En attente d'approbation
AppoinmentStatus: Statut
Meeting: Réunion
MeetingTime: Heure de rendez-vous
MeetingLocation: Lieu de la rencontre
Nullify: Annuler
Reschedule: Reprogrammer
Calendar: Calendrier
BookingCalendar: Calendrier des réservations
Requests: Demandes
BookingRequests: Demandes de réservation
NoOffersYet: Il n'y a pas encore d'offres.
ChoosePhoto: Choisir photo
ChooseImage: Choisir image
Attribution: Attribution
AddOffer: Ajouter offre
Minutes: Minutes
TimeZone: Fuseau horaire
AppointmentTimeIsInThePast: L'heure du rendez-vous est passée
AppointmentDayIsInThePast: Le jour du rendez-vous est passé
BookingSequenceRestarted: La séquence de réservation a redémarré
StartAnew: Recommencer à nouveau
InvalidBookingEntryPoint: Point d'entrée invalide pour la réservation
BookNewAppointment: Prendre un nouveau rendez-vous
ShowDetails: Afficher les détails
YouSuccessfullyCreatedYourBooking: Vous avez créé avec succès votre réservation
BookingStateDiagram: Schéma de transition d'état pour la réservation
InvalidFormData: Données de formulaire incorrectes
MissingForm: Formulaire manquant
SelectedTime: Heure sélectionnée
LoginToIdentifyCustomer: Veuillez vous connecter pour identifier le client
AlreadyHaveAnAccount: Avoir déjà un compte
ContactUs: Contactez-nous
LoginToSeeYourProfile: Veuillez vous connecter pour voir votre profil
End: La fin
UserProfile: Profil de l'utilisateur
RescheduleAppointment: Reprogrammer le rendez-vous
CancelAppointment: Annuler
Appointment: Rendez-vous
NoAppointmentsYet: Vous n'avez pas encore de rendez-vous
LoginToSeeYourAppointments: Veuillez vous connecter pour voir vos rendez-vous
MyAppointments: Mes rendez-vous
Time: Heure
Date: Date
Day: Jour
NotYourAccount: Pas votre compte 
Continue: Continuez
Next: Suivante
StepNofM n m: Étape #{show n} de #{show m}
MyContacts: Mes contacts
TellUsAboutYourself: Parle-nous de toi
CustomerInformation: Informations client
Proceed: Continue
SelectedStaff: Le personnel sélectionné
SelectedServices: Les services sélectionnés
SignUpToContinue: Inscrivez-vous pour continuer
ReceptionTime: Heure d'accueil
AppointmentTime: Heure du rendez-vous
SelectAtLeastOneServicePlease: Sélectionnez au moins un service
SelectStaff: Sélectionner le personnel
MaximumAvailability: Disponibilité maximale
NoPreference: Aucune préférence
NoStaffAvailable: Pas de personnel disponible
SymbolMinute: min
SymbolHour: h
InvalidDurationHourMinute duration: Durée non valide : #{duration}. Modèle attendu HH:MM
Duration: Durée
Offers: Offres
Offer: Offre
ChooseServices: Choose services
ChooseServicesToBook: Choisissez les services à réserver
ChooseService: Choisissez un service
ChooseServiceToBook: Choisissez un service à réserver
Unregister: Désinscrire
NoServicesFound: Aucun service trouvé
Administrator: Administrateur
Customer: Cliente
NoUsersFound: Aucun utilisateur trouvé
More: Plus
Favicon: Icône
NoBrandYet: Il n'y a pas encore de marque
BrandStrapline: Slogan de la marque
BrandName: Nom de la marque
BrandMark: Empreinte de la marque
Brand: Marque
ValueNotInRange rstart rend: Valeur hors plage #{show rstart}..#{show rend}
InvalidValue: Valeur incorrecte
Unregistered: Non enregistré
Registered: Enregistré
AccountStatus: Statut du compte
Employed: Employé
Dismissed: Licencié
Select: Sélectionner
Status: Statut
NoStaffMembersFound: Aucun membre du personnel trouvé
Search: Recherche
UnregisterAreYouSure: Voulez-vous vraiment désinscrire l'utilisateur ?
RegisterAsUser: S'inscrire en tant qu'utilisateur
PasswordChanged: Mot de passe changé
NewPassword: Nouveau mot de passe
ResetPassword: Réinitialiser le mot de passe
NoUsersYet: Il n'y a pas encore d'utilisateurs
User: Utilisateur
Users: Utilisateurs
Contact: Contact
AlreadyExists: Existe déjà
Content: Contenu
NoContentYet: Il n'y a pas encore de contenu
SourceCode: Code source
ErdDiagram: Diagramme ERD
Resources: Ressources
ExpertAlreadyInTheList: Expert déjà dans la liste
RoleAlreadyInTheList: Rôle déjà dans la liste
Ratings: Évaluations
Rating: Notation
AddRole: Ajouter rôle
NoRolesYes: Il n'y a pas encore de rôles
BookAppointment: Prenez rendez-vous
EmployeeAlreadyInTheList: L'employé déjà dans la liste
Mobile: Portable
Phone: Téléphone
Role: Rôle
Roles: Rôles
Employee: Employée
NoStaffYet: Il n'y a pas encore de personnel
AddStaffMember: Ajouter un membre
Staff: Personnelle
No: Non
Yes: Oui
Unpublished: Non publié
Published: Publié
Overview: Aperçu
PriceAlreadyInTheList: Ce prix est déjà dans la liste
Registration: Inscription
Authentication: Authentification
NoPriceSetYet: Aucun prix n'a été fixé pour le service
AddPrice: Ajouter prix
Pricelist: Liste de prix
ServisAlreadyInTheList: Ce service est déjà dans la liste
DuplicateValue: Valeur en double
Suffix: Suffixe
Prefix: Préfixe
PleaseConfirm: Veuillez confirmer
YesDelete: Supprimer
DeleteAreYouSure: Etes-vous sûr que vous voulez supprimer?
AddService: Ajouter service
AddSubservice: Ajouter sous-service
Subservices: Sous-services
Category: Catégorie
Categories: Catégories
Image: Image
NoServicesYet: Il n'y a pas encore de services
RecordDeleted: L'enregistrement a été supprimé
RecordEdited: L'enregistrement a été modifié
RecordAdded: Enregistrement ajouté
Thumbnail: Vignette
Price: Prix
Description: Description
TheName: Nom
Name: Nom
PasswordsDoNotMatch: Les mots de passe ne correspondent pas
YouMustEnterTwoValues: Vous devez entrer deux valeurs
Email: E-mail
FullName: Nom et prénom
Photo: Photo
Save: Enregistrer
Cancel: Annuler
Account: Compte
DoNotHaveAnAccount: Vous n'avez pas de compte ?
AsAdmin: Comme administrateur
CreateAccount: Créer un compte
SignInToYourAccount: Connectez-vous à votre compte
SignIn: Connectez-vous
SignUp: S'inscrire
Logout: Se déconnecter
Login: Connexion
ConfirmPassword: Confirmez le mot de passe
Password: Mot de passe
Username: Nom d'utilisateur
Book: Réserver
Add: Ajouter
Data: Donnés
Welcome: Bienvenue
AboutUs: À propos de nous
Service: Service
Services: Services
Salon: Salon
AppName: Salon
MetaKeywords: beauté, salon, application
MetaDescription: Application de salon de beauté

Documentation: Documentation
Doc001: L'application "Salon" offre la possibilité de publier et d'annoncer les services des propriétaires de salons de beauté sur le Web.

Doc002 hrefServices: Les services à annoncer sont définis dans la section <a href=#{hrefServices}>« Services »</a> du groupe « Données ». Si nécessaire, les services peuvent être définis comme une hiérarchie de groupes et de sous-services.