Photo: Photo
Cancel: Annuler
Account: Compte
DoNotHaveAnAccount: Vous n'avez pas de compte ?
AsAdmin: Comme administrateur
CreateAccount: Créer un compte
SignInToYourAccount: Connectez-vous à votre compte
SignUp: S'inscrire
Logout: Se déconnecter
Login: Connexion
Password: Mot de passe
Username: Nom d'utilisateur
Book: Réserver
Add: Ajouter
Data: Donnés
Welcome: Bienvenue
AboutUs: À propos de nous
Services: Services
Salon: Salon