ServisAlreadyInTheList: Acest serviciu este deja în listă
DuplicateValue: Valoarea duplicată
Suffix: Sufix
Prefix: Prefix
PleaseConfirm: Vă rugăm să confirmați
YesDelete: Șterge
DeleteAreYouSure: Sigur doriți să ștergeți?
AddService: Adaugă serviciu
AddSubservice: Adaugă subserviciu
Subservices: Subservicii
Category: Categorie
Image: Imagine
NoServicesYet: Nu există încă servicii
RecordDeleted: Înregistrarea a fost ștearsă
RecordEdited: Înregistrarea a fost editată
RecordAdded: Înregistrare adăugată
Thumbnail: Miniatură
Price: Preț
Description: Descriere
TheName: Nume
Name: Nume
PasswordsDoNotMatch: Parolele nu se potrivesc
YouMustEnterTwoValues: Trebuie să introduceți două valori
Email: E-mail
FullName: Numele complet
Photo: Foto
Save: Salvează
Cancel: Renunță
Account: Cont
DoNotHaveAnAccount: Nu aveți cont?
AsAdmin: Ca administrator
CreateAccount: Creează cont
SignInToYourAccount: Conectați-vă la contul dvs
SignIn: Conectați-vă
SignUp: Înscriere
Logout: Deconectare
Login: Autentificare
ConfirmPassword: Confirmați parola
Password: Parolă
Username: Nume de utilizator
Book: Rezervați
Add: Adăuga
Data: Date
Welcome: Bine ați venit
AboutUs: Despre noi
Service: Serviciu
Services: Servicii
Salon: Salon