StoreWithSecretManager: Stocați cu Google Secret Manager
StoreInDatabase: Stocați în baza de date
ClearSettings: Ștergeți
Initialize: Inițializează
Tokens: Jetoane
Total: Total
AsPdf: PDF
AsHtml: HTML
Download: Descarcă
SentAsHtml: Trimis ca HTML
SendAsHtml: Trimite ca HTML
PdfAttached: PDF atașat
AttachPdf: Atașează PDF
Message: Mesaj
Sender: Expeditor
Recipient: Destinatar
NoMailYet: Nu există încă niciun e-mail
Mail: Poșta
PaymentDueDate: Data scadentă
MessageNotSent: Mesajul nu a fost trimis
MessageSent: Mesaj trimis
BodyEmail: Mesaj
SubjectEmail: Subiect
FromEmail: De la
ToEmail: Către
Send: Trimite
ActionCancelled: Ceva n-a mers bine. Acțiunea anulată
Amount: Suma
Vat: TVA
Tax: Impozit
Quantity: Cantitate
InvoiceItem: Articol de factură
NoInvoiceItemsYet: Încă nu există articole pe factură
InvoiceItems: Articole
InvoiceAlreadyInTheList: Factură deja în listă
BilledFrom: Facturat de la
BillTo: Factură către
Uncollectible: Necolectabilă
Void: Nulă
Open: Deschisă
Draft: Ciornă
DueDate: Data scadenței
DateCreated: Data creării
InvoiceDate: Data facturii
InvoiceNumber: Număr de factură
Invoice: Factură
OnlineMaps: Hărți online
PaymentGateway: Gateway de plată
PaymentIntentCancelled: Intenția de plată a fost anulată
Pay: Plătiți
PaymentAmount: Suma de plată
TotalPrice: Prețul total
Completion: Finalizare
Checkout: Verifică
PayWithCreditOrDebitCard: Plătiți cu card de credit sau debit
DebitCreditCard: Card de debit/credit
CreditCard: Card de credit
DebitCard: Card de debit
PayNow: Plătiți acum
PayAtVenue: Plata la locatie
PaymentMethod: Modalitate de plată
NoPaymentSettingsYet: Încă nu există setări de plată
Settings: Setări
PaymentSettings: Setări pentru plată
NoInvoicesYet: Încă nu există facturi
Invoices: Facturi
Billing: Facturare
ShowAllMine: Arată toate ale mele
ShowMyAppointments: Afișează programările mele
Success: Succes
Congratulations: Felicitări
Remove: Șterge
RemoveProfileHint: Veți fi deconectat și nu vă veți putea conecta cu acest nume de utilizator
RemoveProfileAreYouSure: Sigur doriți să vă ștergeți profilul?
Removed: Eliminat
Blocked: Blocat
OnlyAdminisHaveAccess: Numai administratorii pot gestiona aceste date
AuthorizationRequired: Este necesară autorizarea
OnlyAnalystsHaveAccess: Doar analiștii au acces la rapoartele analitice
LoginAsAdminToContinue: Vă rugăm să vă conectați ca administrator pentru a continua
LoginAsAnalystToContinue: Vă rugăm să vă conectați ca analist pentru a continua
Analyst: Analist
NoRequestsFoundForThisDay: Nu au fost găsite solicitări pentru această zi
LoginAsEmployeeToContinue: Vă rugăm să vă autentificați ca angajat pentru a continua
LoginToContinue: Vă rugăm să vă conectați pentru a continua
AuthenticationRequired: Este necesară autentificarea
NoAppointmentsForThisDay: Nu aveți programări pentru această zi
Completed: Finalizată
Pending: În așteptare
NoBusinessAddressFound: Nu a fost găsită nicio adresă
ShowAddress: Arată adresa
NoBusinessHoursFound: Nu a fost găsit niciun program de lucru
Sunday: duminică
Saturday: sâmbătă
Friday: vineri
Thursday: joi
Wednesday: miercuri
Tuesday: marţi
Monday: luni
PatternHourMinute: HH:MM
Latitude: Latitudine
Longitude: Longitudine
ShowMap: Arată harta
ShowSchedule: Afișează programul de lucru
NumberOfOrders: Numărul de comenzi
ValueOfOrders: Valoarea comenzilor
TotalOrderValue: Valoarea totală a comenzilor
ServiceRanking: Clasamentul serviciilor
AcronymAOV: AOV
AverageOrderValue: Valoarea medie a comenzii
BasicEntities: Entităţile de bază
BusinessDay: Zi de lucru
SortDescending: Sortează descrescător
SortAscending: Sortare ascendentă
Sort: Sortează
Workday: Zi de lucru
TimeSlot: Interval de timp
CustomerRanking: Clasamentul clienților
TotalScheduledTime: Timp total programat
TotalBookedTime: Timp total rezervat
NoDataFound: Nu s-au gasit date
BetweenTo: Până la
BetweenFrom: De la
Period: Perioada
ChoosePeriod: Alege perioada
CompletionTime: Timpul de finalizare
Today: Astăzi
Mon: lun.
Tue: mar.
Wed: mie.
Thu: joi
Fri: vin.
Sat: sâm.
Sun: dum.
List: Listă
InvalidTimeInterval: Interval de timp nevalid
Holiday: Sărbătoare
Weekend: Zi liberă
Weekday: Zi de lucru
DayType: Tipul zilei
BusinessHours: Orele de lucru
NoBusinessScheduleYet: Programul de lucru nu există încă 
BusinessDays: Zile lucrătoare
Details: Detalii
EndTime: Ora de încheiere
StartTime: Ora de începere
WorkingHours: Orele de lucru
NoScheduleYet: Nu există încă un program de lucru
WorkSchedule: Program
AddWorkingHours: Adaugă orele de lucru
Workload: Volumul de muncă
NumberSign: №
Bookings: Rezervări
NoDataToDisplay: Nu sunt date de afișat
PopularOffers: Oferte populare
Analytics: Analiza
NoAppointmentsFound: Nu au fost găsite programări
MarkWidth: Lățimea imaginii
MarkHeight: Înălțimea imaginii
Currency: Valuta
Unavailable: Indisponibil
Available: Disponibil
TheFullName: Numele complet
NoCategoriesFound: Nu a fost găsită nicio categorie
NoOffersFound: Nu au fost găsite oferte
Unassigned: Nealocat
AreYouSureYouWantToTakeOnThisTask: Sunteți sigur că doriți să vă ocupați de această sarcină?
AssignToMe: Atribuie mie
Nonexpert: Nu sunteți enumerat ca expert pentru acest serviciu 
Back: Înapoi
Close: Închide
Edit: Editează
Del: Șterge
NavigationMenu: Meniul de navigare
OnlyEmployeesMaySeeRequests: Doar angajații pot vedea cererile
YouAreNotAnEmployeeOfFacility: Nu sunteți angajat al acestei unități
InvalidBusinessTimeZone: Fus orar al afacerii nevalid
InvalidBusinessTimeZoneOffset: Compensație nevalidă de fus orar al companiei
InvalidBusinessAddress: Adresa companiei nevalidă
PreviouslySelected: Selectate anterior
TimeZoneOffset: Decalajul de fus orar
AddExpert: Adaugă un expert
NoExpertsYet: Nu există încă experți
Expert: Expert
Experts: Experți
Current: Curent
NoAssigneeRequestReschedule: Dacă reprogramați cererea, sarcina vă va fi atribuită
NoAssigneeRequestApprove: Dacă confirmați această solicitare, sarcina vă va fi transferată
Adjusted: Ajustat
FinishAppointmentConfirm: Vă rugăm să confirmați că cererea clientului a fost îndeplinită și achitată
RequestFinish: Finalizați
BusinessAlreadyExists: Afacerea există deja
NoBusinessYet: Nu există încă nicio afacere
Business: Afacere
Address: Adresă
Location: Locația
ApproveAppointmentConfirm: Vă rugăm să confirmați că ați aprobat această solicitare de programare
FromCoworkers: De la colegi
DemoUserAccounts: Conturi de utilizator Demo
WithoutAssignee: Fără executor
AssignedToMe: Atribuite mie
Assignee: Desemnatul
ShowAll: Arată tot
Approve: Aprobă
Request: Solicitare de programare
LoginToSeeTheRequests: Vă rugăm să vă conectați pentru a vedea solicitările
NoRequestsFound: Nu s-au găsit solicitări
NoPendingRequestsYet: Nu există încă cereri de aprobare
NoRequestsYet: Nu există încă solicitări
AppointmentStateDiagram: Diagrama tranziție de stare a programării
NoHistoryYet: Nu există încă istorie
History: Istoria
EntityNotFound: Entitatea nu a fost găsită
LoginBanner loginHref: Vă rugăm să vă <a href=#{loginHref}>autentificați</a> pentru a efectua acțiunea
LoginToPerformAction: Vă rugăm să vă autentificați pentru a efectua acțiunea
CancelAppointmentReally: Sigur doriți să anulați această întâlnire?
Acquaintance: Fă cunoștință
SayHelloTo: Salută-l pe
Paid: Plătit
Cancelled: Anulată
Approved: Aprobată
AwaitingApproval: Așteaptă aprobarea
AppoinmentStatus: Starea
Meeting: Întâlnire
MeetingTime: Ora întâlnirii
MeetingLocation: Locul de întâlnire
Nullify: Anulează
Reschedule: Reprogramează
Calendar: Calendar
BookingCalendar: Calendar de rezervari
Requests: Solicitări de programare
BookingRequests: Cereri de rezervare
NoOffersYet: Nu există încă oferte
ChoosePhoto: Alege foto
ChooseImage: Alege imagine
Attribution: Atribuire
AddOffer: Adaugă ofertă
Minutes: Minute
TimeZone: Fusul orar
AppointmentTimeIsInThePast: Ora programării este în trecut
AppointmentDayIsInThePast: Ziua programării este în trecut
BookingSequenceRestarted: Secvența de rezervare a fost repornită
StartAnew: Începe din nou
InvalidBookingEntryPoint: Punct de intrare nevalid pentru rezervare
BookNewAppointment: Rezervă o nouă programare
ShowDetails: Arata detaliile
YouSuccessfullyCreatedYourBooking: Ați creat cu succes rezervarea
BookingStateDiagram: Diagrama de tranziție a stării pentru rezervare
InvalidFormData: Date de formular nevalide
MissingForm: Lipsește formularul
SelectedTime: Ora selectată
LoginToIdentifyCustomer: Vă rugăm să vă autentificați pentru a identifica clientul
AlreadyHaveAnAccount: Aveți deja un cont
ContactUs: Contactaţi-ne
LoginToSeeYourProfile: Vă rugăm să vă autentificați pentru a vă vedea profilul
End: Sfârșit
UserProfile: Profilul utilizatorului
RescheduleAppointment: Reprogramează întâlnirea
CancelAppointment: Anulează
Appointment: Programare
NoAppointmentsYet: Nu aveți încă programări
LoginToSeeYourAppointments: Vă rugăm să vă autentificați pentru a vă vedea programările
MyAppointments: Programările mele
Time: Ora
Date: Data
Day: Ziua
NotYourAccount: Nu e contul dvs.
Continue: Continuați
Next: Urmatorul
StepNofM n m: Pasul #{show n} din #{show m}
MyContacts: Contactele mele
TellUsAboutYourself: Spune-ne despre tine
CustomerInformation: Informații despre client
Proceed: Continuă
SelectedStaff: Personalul selectat
SelectedServices: Serviciile selectate
SignUpToContinue: Înregistrează-te pentru a continua
ReceptionTime: Ora de receptie
AppointmentTime: Ora programării
SelectAtLeastOneServicePlease: Selectați cel puțin un serviciu
SelectStaff: Selectați personalul
MaximumAvailability: Disponibilitate maxima
NoPreference: Fară preferinţe
NoStaffAvailable: Nu există personal disponibil
SymbolMinute: min
SymbolHour: h
InvalidDurationHourMinute duration: Durată nevalidă: #{duration}. Modelul așteptat HH:MM
Duration: Durată
Offers: Oferte
Offer: Ofertă
ChooseServices: Alegeți serviciile
ChooseServicesToBook: Alegeți serviciile de rezervat
ChooseService: Alegeți un serviciu
ChooseServiceToBook: Alegeți un serviciu de rezervat
Unregister: Anulează înregistrarea
NoServicesFound: Nu a fost găsit niciun serviciu
Administrator: Administrator
Customer: Client
NoUsersFound: Nu a fost găsit niciun utilizator
More: Mai mult
Favicon: Pictograma
NoBrandYet: Nu există încă nicio marcă
BrandStrapline: Sloganul mărcii
BrandName: Numele mărcii
BrandMark: Amprenta mărcii
Brand: Marca
ValueNotInRange rstart rend: Valoarea nu se află în intervalul #{show rstart}..#{show rend}
InvalidValue: Valoare nevalidă
Unregistered: Neînregistrat
Registered: Înregistrat
AccountStatus: Starea contului
Employed: Angajat
Dismissed: Concediat
Select: Selectează
Status: Starea
NoStaffMembersFound: Nu a fost găsit niciun membru al personalului
Search: Caută
UnregisterAsUser: Anulați înregistrarea ca utilizator
UnregisterAreYouSure: Sigur doriți să anulați înregistrarea utilizatorului?
RegisterAsUser: Înregistrați ca utilizator
PasswordChanged: Parolă schimbată
NewPassword: Parolă nouă
ResetPassword: Reseteaza parola
NoUsersYet: Nu există încă utilizatori
User: Utilizator
Users: Utilizatori
Contact: Contact
AlreadyExists: Deja exista
Content: Conţinut
NoContentYet: Nu există încă conținut
SourceCode: Codul sursă
ErdDiagram: Diagrama ERD
Resources: Resurse
ExpertAlreadyInTheList: Expertul deja în listă
RoleAlreadyInTheList: Rolul deja în listă
Ratings: Evaluări
Rating: Rating
AddRole: Adaugă rol
NoRolesYet: Nu există încă roluri
BookAppointment: Rezervă o programare
EmployeeAlreadyInTheList: Angajatul este deja în listă
Mobile: Mobil
Phone: Telefon
Role: Rol
Roles: Roluri
Employee: Angajat
NoStaffYet: Nu există încă personal
AddStaffMember: Adaugă membru
Staff: Personalul
No: Nu
Yes: Da
Unpublished: Nepublicat
Published: Publicat
Overview: Prezentare generală
PriceAlreadyInTheList: Acest preț este deja în listă
Registration: Înregistrare
Authentication: Autentificare
NoPriceSetYet: Nu a fost stabilit niciun preț pentru serviciu
AddPrice: Adaugă preț
Pricelist: Lista de prețuri
ServisAlreadyInTheList: Acest serviciu este deja în listă
DuplicateValue: Valoarea duplicată
Suffix: Sufix
Prefix: Prefix
PleaseConfirm: Vă rugăm să confirmați
YesDelete: Șterge
DeleteAreYouSure: Sigur doriți să ștergeți?
AddService: Adaugă serviciu
AddSubservice: Adaugă subserviciu
Subservices: Subservicii
Category: Categorie
Categories: Categorii
Image: Imagine
NoServicesYet: Nu există încă servicii
RecordRemoved: Înregistrarea a fost eliminată
RecordDeleted: Înregistrarea a fost ștearsă
RecordEdited: Înregistrarea a fost editată
RecordAdded: Înregistrare adăugată
Thumbnail: Miniatură
Price: Preț
Description: Descriere
TheName: Nume
Name: Nume
PasswordsDoNotMatch: Parolele nu se potrivesc
YouMustEnterTwoValues: Trebuie să introduceți două valori
Email: E-mail
FullName: Numele complet
Photo: Foto
Save: Salvează
Cancel: Renunță
Account: Cont
DoNotHaveAnAccount: Nu aveți cont?
AsAdmin: Ca administrator
CreateNewAccount: Creează un cont nou
CreateAccount: Creează cont
SignInToYourAccount: Conectați-vă la contul dvs
SignIn: Conectați-vă
SignUp: Înscriere
Logout: Deconectare
Login: Autentificare
ConfirmPassword: Confirmați parola
Password: Parolă
Username: Nume de utilizator
Book: Rezervați
Add: Adăuga
Data: Date
Welcome: Bine ați venit
AboutUs: Despre noi
Service: Serviciu
Services: Servicii
Salon: Salon
AppName: Salon
MetaKeywords: frumusețe, salon, aplicație
MetaDescription: Aplicația salon de frumusețe


DemoSampleOne: Faceți clic pe pictograma
DemoSampleTwo: pentru a obține o listă de conturi de utilizator demonstrative


Documentation: Documentație
Doc001 hrefHome: Aplicația <a href=#{hrefHome}>„Salon”</a> oferă posibilitatea de a publica și de a face publicitate serviciilor proprietarilor de saloane de înfrumusețare pe web.

Doc002 hrefServices: Serviciile care vor fi promovate sunt definite și publicate în secțiunea <a href=#{hrefServices}>„Servicii”</a> din grupul „Date”. Dacă este necesar, serviciile pot fi definite ca o ierarhie de grupuri și subservicii.

Doc003: Fiecare serviciu poate avea mai multe oferte cu prețuri corespunzătoare. Ofertele sunt definite pentru fiecare Serviciu în secțiunea „Servicii” din grupul „Date”.

Doc004 hrefServices hrefBook: Odată ce serviciul și ofertele sale sunt definite, serviciul poate fi publicat. Serviciul și ofertele vor fi afișate clientului în secțiunea <a href=#{hrefServices}>„Servicii”</a> și disponibile pentru rezervare în secțiunea <a href=#{hrefBook}>„Rezervă o programare”</a>.

Doc005 hrefBusiness: Informații detaliate despre afacere pot fi furnizate în secțiunea <a href=#{hrefBusiness}>„Afacere”</a> din grupul „Date” din meniul principal.

Doc0061 hrefSchedule hrefBusiness: În plus, din fila <a href=#{hrefSchedule}>„Program”</a> în secțiunea <a href=#{hrefBusiness}>„Afacere”</a>, poate fi adăugat programul de lucru al organizației pentru fiecare zi.

Doc0062 hrefBusiness: În plus, din fila „Program” în secțiunea <a href=#{hrefBusiness}>„Afacere”</a>, poate fi adăugat programul de lucru al organizației pentru fiecare zi.

Doc0063 hrefAboutUs hrefBusiness: Pagina „Despre noi” poate fi personalizată din fila <a href=#{hrefAboutUs}>„Despre noi”</a> din meniul <a href=#{hrefBusiness}>„Afacere”</a> din grupul „Date”.

Doc0064 hrefBusiness: Pagina „Despre noi” poate fi personalizată din fila „Despre noi” din meniul <a href=#{hrefBusiness}>„Afacere”</a> din grupul „Date”.

Doc0065 hrefContactUs hrefBusiness: Pagina „Contacte” poate fi personalizată din fila <a href=#{hrefContactUs}>„Contactați-ne”</a> din meniul <a href=#{hrefBusiness}>„Afacere”</a> din grupul „Date”.

Doc0066 hrefBusiness: Pagina „Contacte” poate fi personalizată din fila „Contactați-ne” din meniul <a href=#{hrefBusiness}>„Afacere”</a> din grupul „Date”.

Doc0067 hrefHome hrefBrand hrefBusiness: Pagina <a href=#{hrefHome}>„Acasă”</a> este personalizabilă din fila <a href=#{hrefBrand}>„Marca”</a> din meniul <a href=#{hrefBusiness}>„Afacere”</a> din grupul „Date”.

Doc0068 hrefHome hrefBusiness: Pagina <a href=#{hrefHome}>„Acasă”</a> este personalizabilă din fila „Marca” din meniul <a href=#{hrefBusiness}>„Afacere”</a> din grupul „Date”.

Doc007: În prezent, aplicația acceptă o singură afacere. Asistența multi-business este planificată pentru versiunile viitoare ale aplicației.

Doc008 href: Utilizatorii aplicației, inclusiv clienți, angajați și administratori, pot fi înregistrați prin intermediul formularului <a href=#{href}>„Înregistrare”</a>.

Doc009 href: De asemenea, utilizatorii pot fi gestionați de administratori în secțiunea <a href=#{href}>„Utilizatori”</a> din grupul „Date”.

Doc010: Un utilizator înregistrat poate avea mai multe roluri în același timp.

Doc011: Un administrator poate atribui rolul „Administrator” oricărui alt utilizator înregistrat. Rolul de „Administrator” este necesar pentru a avea acces la orice secțiune a grupului „Date”. Adică pentru a gestiona configurația și datele aplicației.

Doc012: Un administrator poate atribui rolul „Analist” oricărui alt utilizator înregistrat. Rolul „Analist” este necesar pentru a avea acces la orice secțiune a grupului „Analiza”. Adică pentru a genera rapoarte analitice.

Doc013: Orice utilizator care este înregistrat și ca membru al personalului are rolul „Angajat”. Un utilizator cu rolul „Angajat” are acces la coada de solicitări de servicii.

Doc014: Toți utilizatorii pot deveni clienți prin simpla înregistrare și utilizarea serviciilor oferite.

Doc015: Integrare cu API-uri externe

Doc016 href: Pentru a simula o plată reușită, utilizați carduri de test din <a href=#{href}>lista următoare</a>.

Doc017 href: Pentru a simula plățile pe care emitentul le refuză, utilizați carduri de testare din <a href=#{href}>următoarea listă</a>.

Doc018 href: O factură poate fi creată manual în secțiunea <a href=#{href}>„Facturi”</a>, furnizând detaliile acesteia și elementele constitutive.

Doc019: După crearea unei noi facturi și adăugarea elementelor acesteia, factura poate fi trimisă clientului la o adresă de e-mail specificată.

Doc020: În plus, factura poate fi descărcată în format PDF sau HTML și trimisă clientului prin alte mijloace de comunicare.