RegisterAsUser: Înregistrați ca utilizator
PasswordChanged: Parolă schimbată
NewPassword: Parolă nouă
ResetPassword: Reseteaza parola
NoUsersYet: Nu există încă utilizatori
User: Utilizator
Users: Utilizatori
Contact: Contact
AlreadyExists: Deja exista
Content: Conţinut
NoContentYet: Nu există încă conținut
SourceCode: Codul sursă
ErdDiagram: Diagrama ERD
Resources: Resurse
RoleAlreadyInTheList: Rol deja în listă
Rating: Rating
AddRole: Adăugați un rol
NoRolesYes: Nu există încă roluri
BookAppointment: Rezervă o programare
EmployeeAlreadyInTheList: Angajatul este deja în listă
Mobile: Mobil
Phone: Telefon
Role: Rol
Roles: Roluri
Employee: Angajat
NoStaffYet: Nu există încă personal
AddStaffMember: Adaugă membru
Staff: Personalul
No: Nu
Yes: Da
Published: Publicat
Overview: Prezentare generală
PriceAlreadyInTheList: Acest preț este deja în listă
Registration: Înregistrare
Authentication: Autentificare
NoPriceSetYet: Nu a fost stabilit niciun preț pentru serviciu
AddPrice: Adaugă preț
Pricelist: Lista de prețuri
ServisAlreadyInTheList: Acest serviciu este deja în listă
DuplicateValue: Valoarea duplicată
Suffix: Sufix
Prefix: Prefix
PleaseConfirm: Vă rugăm să confirmați
YesDelete: Șterge
DeleteAreYouSure: Sigur doriți să ștergeți?
AddService: Adaugă serviciu
AddSubservice: Adaugă subserviciu
Subservices: Subservicii
Category: Categorie
Image: Imagine
NoServicesYet: Nu există încă servicii
RecordDeleted: Înregistrarea a fost ștearsă
RecordEdited: Înregistrarea a fost editată
RecordAdded: Înregistrare adăugată
Thumbnail: Miniatură
Price: Preț
Description: Descriere
TheName: Nume
Name: Nume
PasswordsDoNotMatch: Parolele nu se potrivesc
YouMustEnterTwoValues: Trebuie să introduceți două valori
Email: E-mail
FullName: Numele complet
Photo: Foto
Save: Salvează
Cancel: Renunță
Account: Cont
DoNotHaveAnAccount: Nu aveți cont?
AsAdmin: Ca administrator
CreateAccount: Creează cont
SignInToYourAccount: Conectați-vă la contul dvs
SignIn: Conectați-vă
SignUp: Înscriere
Logout: Deconectare
Login: Autentificare
ConfirmPassword: Confirmați parola
Password: Parolă
Username: Nume de utilizator
Book: Rezervați
Add: Adăuga
Data: Date
Welcome: Bine ați venit
AboutUs: Despre noi
Service: Serviciu
Services: Servicii
Salon: Salon
AppName: Salon
MetaKeywords: frumusețe, salon, aplicație
MetaDescription: Aplicația salon de frumusețe

Documentation: Documentație
Doc001: Aplicația „Salon” oferă posibilitatea de a publica și de a face publicitate serviciilor proprietarilor de saloane de înfrumusețare pe web.