PasswordsDoNotMatch: Пароли не совпадают
YouMustEnterTwoValues: Вы должны ввести два значения
Email: Электронная почта
FullName: ФИО
Photo: Фото
Save: Сохранить
Cancel: Отмена
Account: Учетная запись
DoNotHaveAnAccount: Нет учетной записи?
AsAdmin: Как администратор
CreateAccount: Создать учётную запись
SignInToYourAccount: Вход в учетную запись
SignIn: Вход
SignUp: Зарегистрироваться
Logout: Выйти
Login: Войти
ConfirmPassword: Подтвердить пароль
Password: Пароль
Username: Имя пользователя
Book: Бронировать
Add: Добавить
Data: Данные
Welcome: Добро пожаловать
AboutUs: О нас
Service: Услуга
Services: Услуги
Salon: Салон