ShowSchedule: Показать график работы
NumberOfOrders: Количество заказов
ValueOfOrders: Стоимость заказов
TotalOrderValue: Общая стоимость заказов
ServiceRanking: Рейтинг услуг
AcronymAOV: Средний чек
AverageOrderValue: Средняя стоимость заказа
BasicEntities: Основные сущности
BusinessDay: Рабочий день
SortDescending: Сортировать по убыванию
SortAscending: Сортировать по возрастанию
Sort: Сортировать
Workday: Рабочий день
TimeSlot: Временной интервал
CustomerRanking: Рейтинг клиентов
TotalScheduledTime: Общее запланированное время
TotalBookedTime: Общее забронированное время
NoDataFound: Данные не найдены
BetweenTo: По
BetweenFrom: С
Period: Период
ChoosePeriod: Выберите период
CompletionTime: Время выполнения
Today: Сегодня
Mon: пн
Tue: вт 
Wed: ср
Thu: чт
Fri: пт
Sat: сб
Sun: вс
List: Список
InvalidTimeInterval: Неверный интервал времени
Holiday: Праздник
Weekend: Выходной
Weekday: Будний день
DayType: Тип дня
BusinessHours: Рабочее время
NoBusinessScheduleYet: График работы пока не существует
BusinessDays: Рабочие дни
Details: Детали
EndTime: Время окончания
StartTime: Время начала
WorkingHours: Время работы
NoScheduleYet: Графика работы пока нет
WorkSchedule: График
AddWorkingHours: Добавить рабочее время
Workload: Рабочая нагрузка
NumberSign: №
Bookings: Бронирования
NoDataToDisplay: Нет данных для отображенияx
PopularOffers: Популярные предложения
Analytics: Аналитика
NoAppointmentsFound: Записей не найдено
MarkWidth: Ширина изображения
MarkHeight: Высота изображения
Currency: Валюта
Unavailable: Недоступен
Available: Доступен
TheFullName: Полное название
NoCategoriesFound: Категории не найдены
NoOffersFound: Предложений не найдено
Unassigned: Не назначена 
AreYouSureYouWantToTakeOnThisTask: Вы уверены, что хотите взять на себя эту задачу?
AssignToMe: Назначить мне
Nonexpert: Вы не указаны в качестве эксперта по этой услуге
Back: Вернуться
Close: Закрыть
Edit: Редактировать
Del: Удалить
NavigationMenu: Навигационное меню
OnlyEmployeesMaySeeRequests: Запросы могут видеть только сотрудники
YouAreNotAnEmployeeOfFacility: Вы не сотрудник этого учреждения
InvalidBusinessTimeZone: Неверный часовой пояс компании
InvalidBusinessTimeZoneOffset: Неверное смещение часового пояса компании
InvalidBusinessAddress: Неверный адрес компании
PreviouslySelected: Ранее выбрано
TimeZoneOffset: Смещение часового пояса
AddExpert: Добавить эксперта
NoExpertsYet: Экспертов пока нет
Expert: Эксперт
Experts: Эксперты
Current: Текущий
NoAssigneeRequestReschedule: Если вы перенесете заявку, задача будет закреплена за вами
NoAssigneeRequestApprove: Если вы подтвердите этот запрос, задача будет передана вам
Adjusted: Скорректировано
FinishAppointmentConfirm: Пожалуйста, подтвердите, что запрос клиента выполнен и оплачен
RequestFinish: Завершить
BusinessAlreadyExists: Организация уже существует
NoBusinessYet: Организации пока нет
Business: Организация
Address: Адрес
Location: Место
ApproveAppointmentConfirm: Пожалуйста, подтвердите, что вы одобряете этот запрос на встречу
FromCoworkers: От коллег
DemoUserAccounts: Демо-аккаунты
WithoutAssignee: Без исполнителя
AssignedToMe: Назначенные мне
Assignee: Исполнитель
ShowAll: Показать всё
Approve: Утвердить
Request: Запрос на приём
LoginToSeeTheRequests: Пожалуйста, войдите, чтобы увидеть запросы
NoRequestsFound: Запросы не найдены
NoPendingRequestsYet: Запросов на одобрение пока нет
NoRequestsYet: Запросов пока нет
AppointmentStateDiagram: Схема перехода состояний для записи на приём
NoHistoryYet: Истории пока нет
History: История
EntityNotFound: Сущность не найдена
LoginBanner loginHref: Пожалуйста, <a href=#{loginHref}>войдите</a>, чтобы выполнить действие
LoginToPerformAction: Пожалуйста, войдите, чтобы выполнить действие
CancelAppointmentReally: Вы действительно хотите отменить эту встречу?
Acquaintance: Знакомство
SayHelloTo: Поздороваться с
Paid: Оплачено
Cancelled: Отменено
Approved: Утверждено
AwaitingApproval: В ожидании подтверждения
AppoinmentStatus: Состояние
Meeting: Встреча
MeetingTime: Время встречи
MeetingLocation: Место встречи 
Nullify: Аннулировать
Reschedule: Перенести
Calendar: Календарь
BookingCalendar: Календарь бронирования
Requests: Запросы на приём
BookingRequests: Запросы на бронирование
NoOffersYet: Предложений пока нет
ChoosePhoto: Выбрать фото
ChooseImage: Выбрать изображение
Attribution: Атрибуция
AddOffer: Добавить предложение
Minutes: Минуты
TimeZone: Часовой пояс
AppointmentTimeIsInThePast: Время приема в прошлом
AppointmentDayIsInThePast: День приема в прошлом
BookingSequenceRestarted: Последовательность бронирования возобновлена
StartAnew: Начать заново
InvalidBookingEntryPoint: Неверная точка входа для бронирования
BookNewAppointment: Записаться на новый прием
ShowDetails: Показать детали
YouSuccessfullyCreatedYourBooking: Вы успешно создали бронирование
BookingStateDiagram: Диаграмма перехода состояний для бронирования
InvalidFormData: Неверные данные формы
MissingForm: Отсутствует форма
SelectedTime: Выбранное время
LoginToIdentifyCustomer: Пожалуйста, войдите, чтобы назначить заказчик
AlreadyHaveAnAccount: Уже есть учетная запись
ContactUs: Свяжитесь с нами
LoginToSeeYourProfile: Пожалуйста, войдите, чтобы увидеть свой профиль
End: Конец
UserProfile: Профиль пользователя
RescheduleAppointment: Перенести встречу
CancelAppointment: Аннулировать
Appointment: Запись
NoAppointmentsYet: У вас еще нет записей
LoginToSeeYourAppointments: Пожалуйста, войдите, чтобы увидеть ваши записи
MyAppointments: Мои записи на приём
Time: Время
Date: Дата
Day: День
NotYourAccount: Не ваша учетная запись
Continue: Продолжить
Next: Следующий
StepNofM n m: Шаг #{show n} из #{show m}
MyContacts: Мои контакты
TellUsAboutYourself: Расскажите нам о себе
CustomerInformation: Информация о заказчике
Proceed: Продолжить
SelectedStaff: Избранный персонал
SelectedServices: Выбранные услуги
SignUpToContinue: Зарегистрируйтесь, чтобы продолжить
ReceptionTime: Время приема
AppointmentTime: Время встречи
SelectAtLeastOneServicePlease: Пожалуйста, выберите хотя бы одну услугу
SelectStaff: Выберите персонал
MaximumAvailability: Максимальная доступность
NoPreference: Нет предпочтений
NoStaffAvailable: Нет доступных сотрудников
SymbolMinute: мин
SymbolHour: ч
InvalidDurationHourMinute duration: Недопустимая продолжительность: #{duration}. Ожидаемый шаблон ЧЧ:ММ
Duration: Время
Offers: Предложения
Offer: Предложение
ChooseServices: Выберите услуги
ChooseServicesToBook: Выберите услуги для бронирования
ChooseService: Выберите услугу
ChooseServiceToBook: Выберите услугу для бронирования
Unregister: Отменить регистрацию
NoServicesFound: Услуги не найдены
Administrator: Администратор
Customer: Заказчик
NoUsersFound: Пользователей не найдено
More: Больше
Favicon: Значок
NoBrandYet: Бренда еще нет
BrandStrapline: Слоган бренда
BrandName: Название бренда
BrandMark: Отпечаток бренда
Brand: Бренд
ValueNotInRange rstart rend: Значение вне диапазона #{show rstart}..#{show rend}
InvalidValue: Недопустимое значение
Unregistered: Незарегистрированный
Registered: Зарегистрированный
AccountStatus: Статус учетной записи
Employed: Работает
Dismissed: Уволенный
Select: Выбирать
Status: Статус
NoStaffMembersFound: Сотрудников не найдено
Search: Поиск
UnregisterAsUser: Отменить регистрацию пользователя
UnregisterAreYouSure: Вы уверены, что хотите отменить регистрацию пользователя?
RegisterAsUser: Зарегистрировать как пользователь
PasswordChanged: Пароль изменен
NewPassword: Новый пароль
ResetPassword: Сброс пароля
NoUsersYet: Пользователей пока нет
User: Пользователь
Users: Пользователи
Contact: Контакты
AlreadyExists: Уже существует
Content: Содержание
NoContentYet: Контента пока нет
SourceCode: Исходный код
ErdDiagram: ER-диаграмма
Resources: Ресурсы
ExpertAlreadyInTheList: Эксперт уже в списке
RoleAlreadyInTheList: Роль уже в списке
Ratings: Рейтинги
Rating: Рейтинг
AddRole: Добавить роль
NoRolesYet: Ролей пока нет
BookAppointment: Записаться на приём
EmployeeAlreadyInTheList: Сотрудник уже в списке
Mobile: Мобильный
Phone: Телефон
Roles: Роли
Role: Роль
Employee: Сотрудник
NoStaffYet: Персонала пока нет
AddStaffMember: Добавить сотрудника
Staff: Персонал
No: Нет
Yes: Да
Unpublished: Неопубликовано
Published: Опубликовано
Overview: Обзор
PriceAlreadyInTheList: Эта цена уже есть в списке
Registration: Регистрация
Authentication: Аутентификация
NoPriceSetYet: Цена за услугу не установлена
AddPrice: Добавить цену
Pricelist: Прейскурант
ServisAlreadyInTheList: Эта услуга уже есть в списке
DuplicateValue: Дублированное значение
Suffix: Суффикс
Prefix: Префикс
PleaseConfirm: Пожалуйста подтвердите
YesDelete: Удалить
DeleteAreYouSure: Вы уверены, что хотите удалить?
AddService: Добавить услугу
AddSubservice: Добавить подуслугу
Subservices: Подуслуги
Category: Категория
Categories: Категории
Image: Изображение
NoServicesYet: Услуг пока нет
RecordDeleted: Запись удалена
RecordEdited: Запись отредактирована
RecordAdded: Запись добавлена
Thumbnail: Миниатюра
Price: Цена
Description: Описание
TheName: Наименование
Name: Имя
PasswordsDoNotMatch: Пароли не совпадают
YouMustEnterTwoValues: Вы должны ввести два значения
Email: Электронная почта
FullName: ФИО
Photo: Фото
Save: Сохранить
Cancel: Отмена
Account: Учетная запись
DoNotHaveAnAccount: Нет учетной записи?
AsAdmin: Как администратор
CreateNewAccount: Создать новую учетную запись
CreateAccount: Создать учётную запись
SignInToYourAccount: Вход в учетную запись
SignIn: Вход
SignUp: Зарегистрироваться
Logout: Выйти
Login: Войти
ConfirmPassword: Подтвердить пароль
Password: Пароль
Username: Имя пользователя
Book: Бронировать
Add: Добавить
Data: Данные
Welcome: Добро пожаловать
AboutUs: О нас
Service: Услуга
Services: Услуги
Salon: Салон
AppName: Салон
MetaKeywords: салон, красоты, приложение
MetaDescription: Приложение Салон Красоты

Documentation: Документация
Doc001 hrefHome: Приложение <a href=#{hrefHome}>«Салон»</a> предоставляет возможность публиковать и рекламировать услуги владельцев салонов красоты в сети.

Doc002 hrefServices: Рекламируемые услуги определены и опубликованы в разделе <a href=#{hrefServices}>«Услуги»</a> группы «Данные». При желании услуги можно определить как иерархию групп и подуслуг.

Doc003: Каждая услуга может иметь несколько предложений с соответствующими ценами и валютами. Предложения определены для каждой Услуги в разделе «Услуги» в группе «Данные».

Doc004 hrefServices hrefBook: После определения службы и ее предложений ее можно опубликовать. Услуга и предложения будут отображены клиенту в разделе <a href=#{hrefServices}>«Услуги»</a> и доступны для бронирования в разделе <a href=#{hrefBook}>«Записаться на приём»</a>.

Doc005 hrefBusiness: Подробную информацию об организации можно предоставить в разделе <a href=#{hrefBusiness}>«Организация»</a> группы «Данные» главного меню.

Doc0061 hrefSchedule hrefBusiness: Дополнительно в разделе <a href=#{hrefBusiness}>«Организация»</a> на вкладке <a href=#{hrefSchedule}>«График»</a> можно добавить график работы организации на каждый день.

Doc0062 hrefBusiness: Дополнительно в разделе «Организация» на вкладке «График» можно добавить график работы организации на каждый день.

Doc0063 hrefAboutUs hrefBusiness: Страницу «О нас» можно настроить на вкладке <a href=#{hrefAboutUs}>«О нас»</a> в меню <a href=#{hrefBusiness}>«Бизнес»</a> в группе «Данные».

Doc0064 hrefBusiness: Страницу «О нас» можно настроить на вкладке «О нас» в меню <a href=#{hrefBusiness}>«Бизнес»</a> в группе «Данные».

Doc0065 hrefContactUs hrefBusiness: Страницу «Контакты» можно настроить на вкладке <a href=#{hrefContactUs}>«Контакты»</a> в меню <a href=#{hrefBusiness}>«Бизнес»</a> в группе «Данные».

Doc0066 hrefBusiness: Страницу «Контакты» можно настроить на вкладке «Контакты» в меню <a href=#{hrefBusiness}>«Бизнес»</a> в группе «Данные».

Doc007: В настоящее время приложение поддерживает только один бизнес. Поддержка нескольких организаций планируется в будущих версиях приложения.

Doc008 href: Пользователи приложения, включая клиентов, сотрудников и администраторов, могут быть зарегистрированы через форму <a href=#{href}>«Регистрация»</a>.

Doc009 href: Также управлять пользователями администраторы могут в разделе <a href=#{href}>«Пользователи»</a> группы «Данные».