Suffix: Суффикс
Prefix: Префикс
PleaseConfirm: Пожалуйста подтвердите
YesDelete: Удалить
DeleteAreYouSure: Вы уверены, что хотите удалить?
AddService: Добавить услугу
AddSubservice: Добавить подуслугу
Subservices: Подсервисы
Category: Категория
Image: Изображение
NoServicesYet: Услуг пока нет
RecordDeleted: Запись удалена
RecordEdited: Запись отредактирована
RecordAdded: Запись добавлена
Thumbnail: Миниатюра
Price: Цена
Description: Описание
TheName: Наименование
Name: Имя
PasswordsDoNotMatch: Пароли не совпадают
YouMustEnterTwoValues: Вы должны ввести два значения
Email: Электронная почта
FullName: ФИО
Photo: Фото
Save: Сохранить
Cancel: Отмена
Account: Учетная запись
DoNotHaveAnAccount: Нет учетной записи?
AsAdmin: Как администратор
CreateAccount: Создать учётную запись
SignInToYourAccount: Вход в учетную запись
SignIn: Вход
SignUp: Зарегистрироваться
Logout: Выйти
Login: Войти
ConfirmPassword: Подтвердить пароль
Password: Пароль
Username: Имя пользователя
Book: Бронировать
Add: Добавить
Data: Данные
Welcome: Добро пожаловать
AboutUs: О нас
Service: Услуга
Services: Услуги
Salon: Салон